# Deploy an Architect flow from an exported YAML file.
# Terraform reads the YAML definition and sends it to Genesys Cloud.
resource "genesyscloud_architect_flow" "basic_cicd_flow" {
  name        = "${var.environment}-Basic-CICD-Flow"
  description = "Inbound Architect flow deployed from YAML for ${var.environment}"
  published   = true

  # The YAML file is exported from Genesys Architect.
  # It becomes the flow definition for this resource.
  # The flow definition is loaded from the exported YAML file.
  # If you want to replace placeholders in the flow with actual IDs,
  # update the YAML file with names like {{support_queue}} or {{billing_skill}}
  # and add replace() rules in the locals block below.
  definition = local.flow_definition

  tags = [
    var.environment,
    "terraform-managed",
    "architect-flow",
  ]
}

locals {
  # Read the YAML text from the exported Architect flow file.
  raw_flow_yaml = file("${path.module}/Basic_CICD_Flow_v1-0.yaml")

  # Replace placeholder tokens with actual Genesys Cloud IDs from other modules.
  # This is the mapping logic: placeholders in the YAML file get mapped to
  # IDs generated by users, skills, queues, and divisions modules.
  flow_definition = replace(
    replace(
      replace(
        local.raw_flow_yaml,
        "{{support_queue}}", lookup(var.queue_ids, "support", "")),
      "{{billing_skill}}", lookup(var.skill_ids, "billing", "")),
    "{{home_division}}", lookup(var.division_ids, "home_ind", ""))
}
